apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./../../base

namePrefix: development-

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: podinfo
    patch: |-
      spec:
        destination:
          namespace: developemnt-podinfo
