apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

resources:
  - ./base/pod-info-helm.yaml

patchesStrategicMerge:
  - |-
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: podinfo
    spec:
      source:
        targetRevision: "6.0.0"
