apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  destination:
    namespace: development-podinfo
  source:
    targetRevision: 6.0.1
    helm:
      valuesObject:
        ingress:
          className: nginx
          enabled: true
          hosts:
            - host: podinfo.dev.dramisinfo.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - podinfo.dev.dramisinfo.com
              secretName: podinfo-tls
