ingress:
  enabled: true
  hosts:
    - host: podinfo.dev.dramisinfo.com
      paths:
        - path: /
          pathType: Prefix
    tls:
      - secretName: podinfo-tls
        hosts:
          - podinfo.dev.dramisinfo.com
